name: Swift

on: [push]

jobs:
  build:

    runs-on: macos-latest
    defaults:
      run:
        working-directory: Mobile

    steps:
      - uses: actions/checkout@v2
      - run: pwd && ls
      - name: Build
        run: swift package generate-xcodeproj
      # - name: Run tests
      #   run: swift test