name: Swift

on: [push]

jobs:
  build:

    runs-on: macos-latest
    defaults:
      run:
        working-directory: Mobile

    steps:
      - uses: actions/checkout@v2
      - run: pwd && ls
      - name: Build
        run: |
          xcodebuild clean test -project "Mobile.xcproject" -scheme "Mobile" -destination "platform=iOS Simulator,name=iPhone 12 Pro,OS=latest" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
      # - name: Run tests
      #   run: swift test