name: Swift

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2
      - run: pwd && ls
      - name: Build
        run: |
          xcodebuild clean build -project "Mobile.xcodeproj" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
      # - name: Run tests
      #   run: swift test